services:
  website:
    build:
      context: .
      dockerfile: dockerfile
    container_name: website
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-check-certificate", "-qO-", "https://127.0.0.1/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
