services:
  website:
    build:
      context: .
      dockerfile: dockerfile
    container_name: website
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
